name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:11
          apps: sbt
      - name: Check formatting
        run: sbt scalafmtSbtCheck scalafmtCheckAll
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      - name: Test
        run: sbt test
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
